### ISSUE TITLE
dificuldade na instalação

### ISSUE THREAD

**Issue by rafso** [educacaoitajai/erudio#12]
Ao rodar o composer.phar install estou recebendo o seguinte erro:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
Package zendframework/zendpdf is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineMigrationsBundle" from namespace "Doctrine\Bundle\MigrationsBundle".
Did you forget a "use" statement for another namespace? in D:\xampp\htdocs\erudio\erudio-server\app\AppKernel.php on line 17

Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineMigrationsBundle" from namespace "Doctrine\Bundle\MigrationsBundle".
Did you forget a "use" statement for another namespace? in D:\xampp\htdocs\erudio\erudio-server\app\AppKernel.php on line 17

Call Stack:
    0.4992    2078944   1. Symfony\Component\Debug\ErrorHandler->handleException() D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php:0

PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineMigrationsBundle" from namespace "Doctrine\Bundle\MigrationsBundle".
Did you forget a "use" statement for another namespace? in D:\xampp\htdocs\erudio\erudio-server\app\AppKernel.php:17
Stack trace:
#0 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php(448): AppKernel->registerBundles()
#1 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(60): Symfony\Component\HttpKernel\Kernel->boot()
#3 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(122): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Com in D:\xampp\htdocs\erudio\erudio-server\app\AppKernel.php on line 17
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception

  [RuntimeException]
  An error occurred when executing the ""cache:clear --no-warmup"" command:
  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundExcept
  ion: Attempted to load class "DoctrineMigrationsBundle" from namespace "Doc
  trine\Bundle\MigrationsBundle".
  Did you forget a "use" statement for another namespace? in D:\xampp\htdocs\
  erudio\erudio-server\app\AppKernel.php on line 17
  Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load
   class "DoctrineMigrationsBundle" from namespace "Doctrine\Bundle\Migration
  sBundle".
  Did you forget a "use" statement for another namespace? in D:\xampp\htdocs\
  erudio\erudio-server\app\AppKernel.php on line 17
  Call Stack:
      0.4992    2078944   1. Symfony\Component\Debug\ErrorHandler->handleExce
  ption() D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Sym
  fony\Component\Debug\ErrorHandler.php:0
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundE
  xception: Attempted to load class "DoctrineMigrationsBundle" from namespace
   "Doctrine\Bundle\MigrationsBundle".
  Did you forget a "use" statement for another namespace? in D:\xampp\htdocs\
  erudio\erudio-server\app\AppKernel.php:17
  Stack trace:
  #0 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\
  Component\HttpKernel\Kernel.php(448): AppKernel->registerBundles()
  #1 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\
  Component\HttpKernel\Kernel.php(114): Symfony\Component\HttpKernel\Kernel->
  initializeBundles()
  #2 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\
  Bundle\FrameworkBundle\Console\Application.php(60): Symfony\Component\HttpK
  ernel\Kernel->boot()
  #3 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\
  Component\Console\Application.php(122): Symfony\Bundle\FrameworkBundle\Cons
  ole\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), O
  bject(Symfony\Com in D:\xampp\htdocs\erudio\erudio-server\app\AppKernel.php
   on line 17

**Comment by JDias** [comment]
Tentou:

composer require doctrine/doctrine-migrations-bundle

?

**Comment by rafso** [comment]
sim, mas parece que falta algo no comando, ele não acontece nada

**Comment by wjhony** [comment]
rafso, a dependência estava faltando mesmo, já adicionei. Recomendo fazer um git pull para pegar essa atualização e tentar o composer install novamente

**Comment by wjhony** [comment]
a senha do banco, se não existir, deve ser colocada como null, responsendo a pergunta da outra issue.

**Comment by rafso** [comment]
Obrigado, acabei de fazer isso, mas continua com erro:

Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Nothing to install or update
Package zendframework/zendpdf is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineMigrationsBundle" from namespace "Doctrine\Bundle\MigrationsBundle".
Did you forget a "use" statement for another namespace? in D:\xampp\htdocs\erudio\erudio-server\app\AppKernel.php on line 17

Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineMigrationsBundle" from namespace "Doctrine\Bundle\MigrationsBundle".
Did you forget a "use" statement for another namespace? in D:\xampp\htdocs\erudio\erudio-server\app\AppKernel.php on line 17

Call Stack:
    0.4992    2078944   1. Symfony\Component\Debug\ErrorHandler->handleException() D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\Component\Debug\ErrorHandler.php:0

PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineMigrationsBundle" from namespace "Doctrine\Bundle\MigrationsBundle".
Did you forget a "use" statement for another namespace? in D:\xampp\htdocs\erudio\erudio-server\app\AppKernel.php:17
Stack trace:
#0 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php(448): AppKernel->registerBundles()
#1 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php(114): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Console\Application.php(60): Symfony\Component\HttpKernel\Kernel->boot()
#3 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\Component\Console\Application.php(122): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Com in D:\xampp\htdocs\erudio\erudio-server\app\AppKernel.php on line 17
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the symfony-scripts event terminated with an exception


  [RuntimeException]
  An error occurred when executing the ""cache:clear --no-warmup"" command:
  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundExcept
  ion: Attempted to load class "DoctrineMigrationsBundle" from namespace "Doc
  trine\Bundle\MigrationsBundle".
  Did you forget a "use" statement for another namespace? in D:\xampp\htdocs\
  erudio\erudio-server\app\AppKernel.php on line 17
  Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load
   class "DoctrineMigrationsBundle" from namespace "Doctrine\Bundle\Migration
  sBundle".
  Did you forget a "use" statement for another namespace? in D:\xampp\htdocs\
  erudio\erudio-server\app\AppKernel.php on line 17
  Call Stack:
      0.4992    2078944   1. Symfony\Component\Debug\ErrorHandler->handleExce
  ption() D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Sym
  fony\Component\Debug\ErrorHandler.php:0
  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundE
  xception: Attempted to load class "DoctrineMigrationsBundle" from namespace
   "Doctrine\Bundle\MigrationsBundle".
  Did you forget a "use" statement for another namespace? in D:\xampp\htdocs\
  erudio\erudio-server\app\AppKernel.php:17
  Stack trace:
  #0 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\
  Component\HttpKernel\Kernel.php(448): AppKernel->registerBundles()
  #1 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\
  Component\HttpKernel\Kernel.php(114): Symfony\Component\HttpKernel\Kernel->
  initializeBundles()
  #2 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\
  Bundle\FrameworkBundle\Console\Application.php(60): Symfony\Component\HttpK
  ernel\Kernel->boot()
  #3 D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\
  Component\Console\Application.php(122): Symfony\Bundle\FrameworkBundle\Cons
  ole\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), O
  bject(Symfony\Com in D:\xampp\htdocs\erudio\erudio-server\app\AppKernel.php
   on line 17

**Comment by wjhony** [comment]
Tente remover seu arquivo composer.lock e depois realizar nova tentativa de instalação. 
Confira antes se no composer.json existe essa linha: 

"doctrine/doctrine-migrations-bundle": "^1.0",

**Comment by rafso** [comment]
já tinha verificado o composer.json e estava correto, apagango o .lock funcionou, muito obrigado, porém agora aparece erro ao tentar logar com admin 123456:


error | {…}
-- | --
code | 500
message | Internal Server Error
exception | […]
0 | Symfony\Component\Debug\Exception\UndefinedFunctionException
message | Attempted to call function "openssl_error_string" from namespace "Lexik\Bundle\JWTAuthenticationBundle\Services\KeyLoader".
class | Symfony\Component\Debug\Exception\UndefinedFunctionException
trace | […]
0 | {…}
namespace |  
short_class |  
class |  
type |  
function |  
file | D:\xampp\htdocs\erudio\erudio-server\vendor\lexik\jwt-authentication-bundle\Services\KeyLoader\OpenSSLKeyLoader.php
line | 29
args | []
1 | Lexik\Bundle\JWTAuthenticationBundle\Services\KeyLoader\OpenSSLKeyLoader
namespace | Lexik\Bundle\JWTAuthenticationBundle\Services\KeyLoader
short_class | OpenSSLKeyLoader
class | Lexik\Bundle\JWTAuthenticationBundle\Services\KeyLoader\OpenSSLKeyLoader
type | ->
function | loadKey
file | D:\xampp\htdocs\erudio\erudio-server\vendor\lexik\jwt-authentication-bundle\Services\JWSProvider\DefaultJWSProvider.php
line | 82
args | […]
0 | […]
2 | Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\DefaultJWSProvider
namespace | Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider
short_class | DefaultJWSProvider
class | Lexik\Bundle\JWTAuthenticationBundle\Services\JWSProvider\DefaultJWSProvider
type | ->
function | create
file | D:\xampp\htdocs\erudio\erudio-server\vendor\lexik\jwt-authentication-bundle\Encoder\DefaultEncoder.php
line | 35
args | […]
0 | […]
3 | Lexik\Bundle\JWTAuthenticationBundle\Encoder\DefaultEncoder
namespace | Lexik\Bundle\JWTAuthenticationBundle\Encoder
short_class | DefaultEncoder
class | Lexik\Bundle\JWTAuthenticationBundle\Encoder\DefaultEncoder
type | ->
function | encode
file | D:\xampp\htdocs\erudio\erudio-server\vendor\lexik\jwt-authentication-bundle\Services\JWTManager.php
line | 60
args | […]
4 | Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager
namespace | Lexik\Bundle\JWTAuthenticationBundle\Services
short_class | JWTManager
class | Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager
type | ->
function | create
file | D:\xampp\htdocs\erudio\erudio-server\src\AuthBundle\Controller\AuthenticationController.php
line | 72
args | […]
5 | AuthBundle\Controller\AuthenticationController
namespace | AuthBundle\Controller
short_class | AuthenticationController
class | AuthBundle\Controller\AuthenticationController
type | ->
function | getTokenAction
file | D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php
line | 151
args | […]
6 | Symfony\Component\HttpKernel\HttpKernel
namespace | Symfony\Component\HttpKernel
short_class | HttpKernel
class | Symfony\Component\HttpKernel\HttpKernel
type | ->
function | handleRaw
file | D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\HttpKernel.php
line | 68
args | […]
7 | Symfony\Component\HttpKernel\HttpKernel
namespace | Symfony\Component\HttpKernel
short_class | HttpKernel
class | Symfony\Component\HttpKernel\HttpKernel
type | ->
function | handle
file | D:\xampp\htdocs\erudio\erudio-server\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Kernel.php
line | 169
args | […]
8 | Symfony\Component\HttpKernel\Kernel
namespace | Symfony\Component\HttpKernel
short_class | Kernel
class | Symfony\Component\HttpKernel\Kernel
type | ->
function | handle
file | D:\xampp\htdocs\erudio\erudio-server\web\app_dev.php
line | 19
args | […]

**Comment by wjhony** [comment]
Não existir a função "openssl_error_string"  indica que o módulo OpenSSL do PHP não está instalado ou não está ativado no seu servidor, ele é necessário para parte de autenticação dos usuários. Você pode buscar orientações neste link: http://php.net/manual/pt_BR/openssl.installation.php. 
Peço desculpas por nossas instruções de instalação anida não abordarem estes aspectos melhor, na verdade ainda estamos elaborando um manual completo mais adequado, e vamos buscar meios de facilitar o processo de instalação futuramente.

**Comment by farribeiro** [comment]
Amigo @rafso , tome cuidado ao usar a hashtag, pois aqui referencia outras issue.
