### ISSUE TITLE
Troca de expertise

### ISSUE THREAD

**Issue by farribeiro** [educacaoitajai/erudio#3]
Gostaria de sugerir inclusão do projeto ao Software Público Brasileiro. Também a possibilidade de fusão ou troca de expertise com o projeto i-Educar

https://softwarepublico.gov.br/gitlab/groups/i-educar

PS: Existe um repositório no github mantido pelo time do i-Educar porém está abandonado

**Comment by educacaoitajai** [comment]
Obrigado pela sugestão Fábio, certamente pretendemos fazer isso em breve, apenas queremos antes finalizar algumas refatorações que estamos fazendo na aplicação, bem como atualizar a documentação e criar manuais para os usuários. Pretendemos garantir que o Erudio seja lançado no portal como um sistema estável, testado e bem documentado.

Quanto ao i-Educar, ele foi desenvolvido também aqui em Itajaí, e era usado até fim do ano passado. Já usamos ele como ponto de partida quanto às funcionalidades que o Erudio deveria oferecer, com alguns ajustes que consideramos pertinentes. Uma vez que iremos migrar nossos dados do i-Educar para o Erudio, provavelmente compartilharemos também os scripts usados para realizar este procedimento.

**Comment by farribeiro** [comment]
O i-Educar não encontrei a autoria do software, é o seu time que o mantém?

**Comment by educacaoitajai** [comment]
Não, o time que criou o i-Educar se dissolveu há vários anos atrás. A versão dele que temos rodando em nosso município é derivada diretamente da original, e já foi modificada por várias pessoas no decorrer dos anos, porém nenhuma destas modificações foi compartilhada com a comunidade.

Alguns detalhes no link: [](https://softwarepublico.gov.br/social/i-educar/blog/novos-recursos-e-melhorias-desenvolvidos-em-2016)

**Comment by farribeiro** [comment]
Quem é que está por trás do software que encontra no SPB? que está ativo. O link é esse que tá no issue. Tem commit de dias

**Comment by educacaoitajai** [comment]
Infelizmente não tenho essa informação, não sei se há um time fixo tocando o projeto lá.

**Comment by farribeiro** [comment]
recomendaria ficara a par do que acontece com este projeto.

**Comment by farribeiro** [comment]
Olá... Marquei-me para receber notificações do projeto i-Educar, fiz um alerta para um desenvolvedor então veio o líder da comunidade hospedado na SPB, @gustin , com o seguinte comentário no PR https://github.com/ieducar/ieducar/pull/10#issuecomment-330429252

**Comment by farribeiro** [comment]
FYI

O projeto i-educar no github será reativado e deixará o SPB. Acredito que haverá nova liderança.

Abraços.

**Comment by farribeiro** [comment]
Issue https://github.com/ieducar/ieducar/issues/20
