### ISSUE TITLE
problema para logar

### ISSUE THREAD

**Issue by JDias** [educacaoitajai/erudio#7]
Aparentemente a instalação funcionou, mas não consigo logar.

e não tenho http://localhost/erudio/erudio-server/web/api/tokens

(o erro pelo que entendi é um not found, mas esse eu tenho)

Source map error: request failed with status 404
Resource URL: http://localhost/erudio/erudio-front/lib/js/angular/newangular.min.js
Source Map URL: angular.min.js.map[Learn More]

**Comment by wjhony** [comment]
/api/tokens não é um arquivo, e sim uma rota, que deve ser interpretada pelo Symfony. O único arquivo PHP que será acessado publicamente é o app.php, dentro da pasta web. Seu PHP é executado por FPM ou como módulo em um servidor Apache? Vocẽ consegue visualizar a página inicial (de login)?

**Comment by JDias** [comment]
Olá,

Sim, me retorna o erro do angular, mas a rota do tokens retorna not found.

Suspeito de problema nas permissões de pasta (seria legal uma pagina de
checkup da instalação, acho)

Não sei em que modo o php está rodando (mas provavelmente deve ser o modo
padrão do Ubuntu)

Em 26 de fev de 2018 3:50 PM, "Jhony" <notifications@github.com> escreveu:

**Comment by JDias** [comment]
Olá,

Sim, me retorna o erro do angular, mas a rota do tokens retorna not found.

Suspeito de problema nas permissões de pasta (seria legal uma pagina de checkup da instalação, acho)

Não sei em que modo o php está rodando (mas provavelmente deve ser o modo padrão do Ubuntu)

**Comment by JDias** [comment]
Olá @wjhony ,
Talvez eu não tenha configurado alguma coisa no url rewrite ?

**Comment by JDias** [comment]
o api/tokens 404 era o rewrite que não estava funcionando, problema no meu vhost. Solved!
agora o angular, acho e espero que seja permissão de pasta errada, pq senão estou sem ideias.

**Comment by JDias** [comment]
agora que o rewrite está funcionando recebo também o um warning:
`Requisição cross-origin bloqueada: A política de mesma origem (Same Origin Policy) impede a leitura do recurso remoto em http://localhost/erudio/erudio-server/web/api/tokens. (Motivo: o cabeçalho CORS 'Access-Control-Allow-Origin' não está presente).`

estou em erudio.local (url)

**Comment by JDias** [comment]
o erro especifico:

```
Error: error.data is null
$scope.login/<@http://erudio.local/erudio-front/app/modules/login/controllers/loginController.js:132:21
f/<@http://erudio.local/erudio-front/lib/js/angular/newangular.min.js:120:182
$eval@http://erudio.local/erudio-front/lib/js/angular/newangular.min.js:134:489
$digest@http://erudio.local/erudio-front/lib/js/angular/newangular.min.js:132:1
$apply@http://erudio.local/erudio-front/lib/js/angular/newangular.min.js:135:267
l@http://erudio.local/erudio-front/lib/js/angular/newangular.min.js:87:150
F@http://erudio.local/erudio-front/lib/js/angular/newangular.min.js:91:187
e@http://erudio.local/erudio-front/lib/js/angular/newangular.min.js:92:271
```

**Comment by JDias** [comment]
Ok, como eu ajustei o vhost, fiz alterações no erudioConfig.js para refletir as mudanças, isso tirou o aviso sobre cors e o erro sumiu, mas não consigo logar e o token agora me retorna "não autorizado".

para acessar as urls de api e docs eu preciso estar logado?

**Comment by JDias** [comment]
eu queria ver se conseguia fazer algo assim no erudioConfig.js

`console.log(erudioConfig.service.ErudioConfig);`

para poder verificar se os paths estão indo certo, mas não estou conseguindo :/

**Comment by JDias** [comment]
acho que chegamos em algum lugar @wjhony :)
o usuario é 76133334851 , mas a senha esta falhando em carregar a private key (senha errada, se uso a senha que coloquei na chave ele pede para consertar a senha, fiz com 7 caracteres)
```

POSTXHRhttp://erudio.local/erudio-server/web/api/tokens[HTTP/1.1 500 Internal Server Error 3057ms] 
HeadersCookiesParamsResponseTimingsStack TraceJSONerror{…}code500messageInternal Server Errorexception[…]0RuntimeExceptionmessageFailed to load private key "/home/jaime/projetos/erudio/erudio-server/app/../var/jwt/private.pem": 
 0906A068:PEM routines:PEM_do_header:bad password readclassRuntimeExceptiontrace[…]0{…}namespaceshort_classclasstypefunctionfile/home/jaime
```

**Comment by wjhony** [comment]
Creio que faltou um detalhe que não está claro nas instruções no README, no arquivo parameters.yml você precisa modificar o parâmetro jwt_key_pass_phrase, com a senha que você usou para gerar a chave privada. Exemplo:  jwt_key_pass_phrase: '123'. Após adicionar, teste o login com o usuário 76133334851 e senha 123456

**Comment by JDias** [comment]
verdade, mas mesmo assim estava dando problema e a senha para o token estava sendo passado MTIzNDU2.

Agora com essa sua mega dica ele "logou" e foi para um path acima do webroot http://erudio.local/#/ (ao invés de/ erudio/erudio-front/ ele foi para /erudio/

(que deve ser alguma daquelas configurações de path)

obrigado!

**Comment by rafso** [comment]
Também estou com problema ao logar após a instalação, segui as dicas informadas, mas o meu erro é de servidor erro 500:

ClassNotFoundException                                                                          Attempted to load class "DoctrineMigrationsBundle" from namespace "Doctrine\Bundle\MigrationsBundle". Did you forget a "use" statement for another namespace?
--
in AppKernel.php (line 17)
at AppKernel->registerBundles()in Kernel.php (line 448)
at Kernel->initializeBundles()in Kernel.php (line 114)
at Kernel->boot()in Kernel.php (line 166)
at Kernel->handle(object(Request))in app_dev.php (line 19)

**Comment by rafso** [comment]
Uma outra dúvida que pode ter relação, nos dados de banco, nome do banco, usuário e senha, é preciso colocar aspas?
Outra coisa, meu banco local está sem senha por padrão, deixo em branco, coloco '' ou escrevo null?

**Comment by JDias** [comment]
Você precisa adicionar o doctrine migrations ao composer.

**Comment by JDias** [comment]
eu consigo pegar o token, mas depois dai não tenho a mínima ideia qual é a forma que eu retorno ele vinculando a uma sessão de usuário!

**Comment by JDias** [comment]
Bom, aos poucos vou caminhando. (security.yml)

    token_extractors:
        authorization_header:
            prefix:  Bearer
            name:    JWT-Authorization

**Comment by rafso** [comment]
obrigado, abri um outro issue, estou tendo problema no composer install com o migrations mesmo, o composer que vem por padrão não está correto? preciso add manualmente algo?

**Comment by wjhony** [comment]
JDias - se você está tentando consultar serviços da API via algum console REST ou algo assim, deve adicionar o cabeçalho com o token em cada requisição, como o frontend faz, o servidor REST não cria uma sessão.
O cabeçalho é o 'JWT-Authorization', com o valor 'Bearer string-do-token'
Estou encerrando esta issue

**Comment by marianagarciaferreira** [comment]
estou com mesmo problema de rota  para api no nginx
